import requests
import ast
import json

url = "http://ceadmclaro.clarochile.cl/modulos/televenta/Obtenercalle.php"

comunas =["AISEN","ALGARROBO","ALHUE","ALTO BIO BIO","ALTO DEL CARMEN","ALTO HOSPICIO","ANCUD","ANDACOLLO","ANGOL","ANTOFAGASTA","ANTUCO","ARAUCO","ARICA","AYSEN","BUIN","BULNES","CABILDO","CABO DE HORNOS","CABRERO","CALAMA","CALBUCO","CALDERA","CALERA","CALERA DE TANGO","CALLE LARGA","CAMARONES","CAMINA","CANELA","CANETE","CARAHUE","CARTAGENA","CASABLANCA","CASTRO","CATEMU","CAUQUENES","CERRILLOS","CERRO NAVIA","CHAITEN","CHANARAL","CHANCO","CHEPICA","CHIGUAYANTE","CHILE CHICO","CHILLAN","CHILLAN VIEJO","CHIMBARONGO","CHOL CHOL","CHONCHI","CISNES","COBQUECURA","COCHAMO","COCHRANE","CODEGUA","COELEMU","COIHAIQUE","COIHUECO","COINCO","COLBUN","COLCHANE","COLINA","COLLIPULLI","COLTAUCO","COMBARBALA","CONCEPCION","CONCHALI","CONCON","CONSTITUCION","CONTULMO","COPIAPO","COQUIMBO","CORONEL","CORRAL","COYHAIQUE","CUNCO","CURACAUTIN","CURACAVI","CURACO DE VELEZ","CURANILAHUE","CURARREHUE","CUREPTO","CURICO","DALCAHUE","DIEGO DE ALMAGRO","DONIHUE","EL BOSQUE","EL CARMEN","EL MONTE","EL QUISCO","EL TABO","EMPEDRADO","ERCILLA","ESTACION CENTRAL","FLORIDA","FREIRE","FREIRINA","FRESIA","FRUTILLAR","FUTALEUFU","FUTRONO","GALVARINO","GORBEA","GRANEROS","GUAITECAS","HIJUELAS","HUALAIHUE","HUALANE","HUALPEN","HUALQUI","HUARA","HUASCO","HUECHURABA","ILLAPEL","INDEPENDENCIA","IQUIQUE","ISLA DE MAIPO","ISLA DE PASCUA","JUAN FERNANDEZ","LA CALERA","LA CISTERNA","LA CRUZ","LA ESTRELLA","LA FLORIDA","LA GRANJA","LA HIGUERA","LA LIGUA","LA PINTANA","LA REINA","LA SERENA","LA UNION","LAGO RANCO","LAGO VERDE","LAGUNA BLANCA","LAJA","LAMPA","LANCO","LAS CABRAS","LAS CONDES","LAUTARO","LEBU","LICANTEN","LIMACHE","LINARES","LITUECHE","LLAILLAY","LLANQUIHUE","LLAYLLAY","LO BARNECHEA","LO ESPEJO","LO PRADO","LOLOL","LONCOCHE","LONGAVI","LONQUIMAY","LOS ALAMOS","LOS ANDES","LOS ANGELES","LOS LAGOS","LOS MUERMOS","LOS SAUCES","LOS VILOS","LOTA","LUMACO","MACHALI","MACUL","MAFIL","MAIPU","MALLOA","MARCHIG\u00dcE","MARIA ELENA","MARIA PINTO","MARIQUINA","MAULE","MAULLIN","MEJILLONES","MELIPEUCO","MELIPILLA","MOLINA","MONTE PATRIA","MOSTAZAL","MULCHEN","NACIMIENTO","NANCAGUA","NATALES","NAVIDAD","NEGRETE","NINHUE","NIQUEN","NOGALES","NUEVA IMPERIAL","NUNOA","O'HIGGINS","OLIVAR","OLLAG\u00dcE","OLMUE","OSORNO","OVALLE","PADRE HURTADO","PADRE LAS CASAS","PAIGUANO","PAIHUANO","PAILLACO","PAINE","PALENA","PALMILLA","PANGUIPULLI","PANQUEHUE","PAPUDO","PAREDONES","PARRAL","PEDRO AGUIRRE CERDA","PELARCO","PELLUHUE","PEMUCO","PENAFLOR","PENALOLEN","PENCAHUE","PENCO","PERALILLO","PERQUENCO","PETORCA","PEUMO","PICA","PICHIDEGUA","PICHILEMU","PINTO","PIRQUE","PITRUFQUEN","PLACILLA","PORTEZUELO","PORVENIR","POZO ALMONTE","PRIMAVERA","PROVIDENCIA","PTO.SAAVEDRA","PUCHUNCAVI","PUCON","PUDAHUEL","PUENTE ALTO","PUERTO MONTT","PUERTO NATALES","PUERTO OCTAY","PUERTO VARAS","PUMANQUE","PUNITAQUI","PUNTA ARENAS","PUQUELDON","PUREN","PURRANQUE","PUTAENDO","PUTRE","PUYEHUE","QUEILEN","QUELLON","QUEMCHI","QUILACO","QUILICURA","QUILLECO","QUILLON","QUILLOTA","QUILPUE","QUINCHAO","QUINTA DE TILCOCO","QUINTA NORMAL","QUINTERO","QUIRIHUE","RANCAGUA","RANQUIL","RAUCO","RECOLETA","RENAICO","RENCA","RENGO","REQUINOA","RETIRO","RINCONADA","RIO BUENO","RIO CLARO","RIO HURTADO","RIO IBANEZ","RIO NEGRO","RIO VERDE","ROMERAL","SAAVEDRA","SAGRADA FAMILIA","SALAMANCA","SAN ANTONIO","SAN BERNARDO","SAN CARLOS","SAN CLEMENTE","SAN ESTEBAN","SAN FABIAN","SAN FELIPE","SAN FERNANDO","SAN GREGORIO","SAN IGNACIO","SAN JAVIER","SAN JOAQUIN","SAN JOSE DE MAIPO","SAN JUAN DE LA COSTA","SAN MIGUEL","SAN NICOLAS","SAN PABLO","SAN PEDRO","SAN PEDRO DE ATACAMA","SAN PEDRO DE LA PAZ","SAN RAFAEL","SAN RAMON","SAN ROSENDO","SAN VICENTE","SANTA ANA","SANTA BARBARA","SANTA CRUZ","SANTA JUANA","SANTA MARIA","SANTIAGO","SANTO DOMINGO","SIERRA GORDA","TALAGANTE","TALCA","TALCAHUANO","TALTAL","TEMUCO","TENO","TEODORO SCHMIDT","TIERRA AMARILLA","TILTIL","TIMAUKEL","TIRUA","TOCOPILLA","TOLTEN","TOME","TORRES DEL PAINE","TORTEL","TRAIGUEN","TREGUACO","TUCAPEL","VALDIVIA","VALLENAR","VALPARAISO","VICHUQUEN","VICTORIA","VICUNA","VILCUN","VILLA ALEGRE","VILLA ALEMANA","VILLARRICA","VINA DEL MAR","VITACURA","YERBAS BUENAS","YUMBEL","YUNGAY","ZAPALLAR"]

datos_comunas = {}

for comuna in comunas:
    payload = {'comuna': f'{comuna}'}
    files = []
    headers = {
        'Cookie': 'PHPSESSID=lh67pp1cenr99coph65g59tv96'
    }

    response = requests.request("POST", url, headers=headers, data=payload, files=files)
    try:
        # Verifica si la respuesta indica un error
        if 'Undefined variable: calle' in response.text:
            print(f"Error para la comuna {comuna}: Variable 'calle' no definida")
            datos_comunas[comuna] = []  # Asigna una lista vacía para indicar un error
        else:
            lista = ast.literal_eval(response.text)
            datos_comunas[comuna] = lista
    except (SyntaxError, ValueError) as e:
        print(f"Error para la comuna {comuna}: {e}")
        datos_comunas[comuna] = []  # Asigna una lista vacía para indicar un error

# Guardar datos_comunas en un archivo JSON
with open('datos_comunas.json', 'w') as json_file:
    json.dump(datos_comunas, json_file)

# Imprimir los datos resultantes
#print(json.dumps(datos_comunas, indent=4))
